version: '3.8'

services:
  java-app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../src:/home/app/src
      - ../pom.xml:/home/app/pom.xml
    container_name: loan-simulator